apiVersion: autoscaling/v2 #By default the autoscaler runs every 15 seconds
kind: HorizontalPodAutoscaler
metadata:
  name: python-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment #The type we are targeting
    name: python-deployment #The target deployment of the autoscaling
  minReplicas: 1 #Minimum pods
  maxReplicas: 1 #Maximum pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80 #How many percent of the minimum allocated resource is used. Can also be changed to absolute values.