apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-grafana-ingressroute
  namespace: default 
spec:
  entryPoints:
    - web 
  routes:    
    - match: PathPrefix(`/lol`)
      kind: Rule
      priority: 1
      services:
        - name: frontend-service
          port: 8080
