apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-ingressroute
  namespace: default
spec:
  entryPoints:
    - web  # HTTP entry point (port 80)
  routes:
    - match: PathPrefix(`/grafana`)
      kind: Rule
      priority: 10
      services:
        - name: kube-prometheus-stack-grafana.prometheus-grafana.svc.cluster.local
          port: 80
          
    - match: PathPrefix(`/`)  # Matches all requests
      kind: Rule
      priority: 1
      services:
        - name: frontend-service    # Kubernetes service for the API
          port: 8080
