apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment #Name of the deployment in the namespace
  labels:
    app: api #Used to select and manage pods with this label
spec: #The desired state of the deployment
  replicas: 1 #Amount of replicas we want !!!! inital amount HPA will change this
  selector: #Defines how the deployment selects pods to manage
    matchLabels: #Matches label to the label of pods with the same label
      app: api #Name of the label of the pods we want to manage
  template: #Template for the pods
    metadata:
      labels:
        app: api #Matches with the selector
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - storage-node  # Only schedule on nodes with this label
      containers:
      - name: api
        image: p7project/api-backend:2.0rc2
        resources: #Sets the allowed amount of resources for the container
            requests: #This is the resources required by each container
              cpu: 200m #100 milliCPU (10% of one CPU core)
              memory: 200Mi
        ports:
        - name: http-port
          containerPort: 8080 #What port the container is listening on
        envFrom:
          - secretRef:
              name: api-secret
          - configMapRef:
              name: api-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP
  selector:
    app: api #Must be the same as the pod label in deployment under "template"
  ports:
    - name: api-service-port
      protocol: TCP
      port: 8080 #The port the service is listening on
      targetPort: http-port #Target port (The port of the pods)
