apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres-api
  POSTGRES_USER: postgres-api-user
  POSTGRES_PASSWORD: postgres-api-password